sudo: required
services:
  - docker

before_install:
  - docker build -t ryleysill/docker-react -f Dockerfile.dev .

script: # series of commands to be executed
  - docker run ryleysill/docker-react npm run test -- --coverage
