version: '3'

services:
  frontend:
    build:
      context: .  # where we want all the files and folders to come from
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules  # dont copy over node_modules
      - .:/app  # takes what in the current directory and copy it over to /app
